import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Terms of Use | SchedAI",
  description: "Terms of Use for SchedAI."
};

const sections = [
  {
    id: "about",
    title: "About SchedAI",
    body: [
      "SchedAI is a personal schedule planning tool for university students. It helps users upload a university-provided schedule file, choose subjects and class sections, set scheduling preferences, and generate possible weekly timetables.",
      "SchedAI is intended to be used as a guide before enrollment. It is not an official enrollment system, university portal, student information system, or replacement for any official university registration process."
    ]
  },
  {
    id: "acceptance",
    title: "Acceptance of Terms",
    body: [
      "By using SchedAI, you agree to these Terms of Use. If you do not agree with these terms, do not use the application.",
      "These terms apply to the hosted website, local development versions, exported schedules, and any related SchedAI functionality."
    ]
  },
  {
    id: "purpose",
    title: "Purpose of the Application",
    body: [
      "SchedAI is designed to help students compare available class sections, avoid overlapping schedules, choose preferred professors, rooms, days, and time slots, protect vacant or break times, and generate possible weekly schedules.",
      "SchedAI is a planning assistant only. Final enrollment decisions must always be verified through the official university system."
    ]
  },
  {
    id: "affiliation",
    title: "No Official University Affiliation",
    body: [
      "SchedAI is independently created by Karl Austin B. Pavia. Unless clearly stated otherwise, SchedAI is not affiliated with, endorsed by, sponsored by, or officially connected to any university, college, department, registrar, enrollment office, or academic institution.",
      "Any university schedule file uploaded by a user remains the user's responsibility."
    ]
  },
  {
    id: "responsibility",
    title: "User Responsibility",
    body: [
      "You are responsible for checking the accuracy of any schedule generated by SchedAI. Before relying on a generated schedule, verify subject codes, subject names, class sections, professors, rooms, days, start times, end times, units, enrollment availability, official restrictions, prerequisites, curriculum requirements, slots, capacity, and any university changes after the schedule file was released.",
      "SchedAI may help organize schedule choices, but it cannot guarantee that a generated schedule is officially valid, available, or enrollable."
    ]
  },
  {
    id: "uploads",
    title: "File Uploads and Parsing",
    body: [
      "SchedAI supports text-based PDF, CSV, and XLSX or Excel files. Scanned image PDFs are not supported unless the text can be extracted by the browser.",
      "Because schedule files may use different layouts, formatting, abbreviations, or table structures, parsing may not always be perfect. SchedAI may misread, miss, duplicate, or incorrectly classify schedule records. Always review parsed subjects and sections before generating or using a schedule."
    ]
  },
  {
    id: "generated",
    title: "Generated Schedules",
    body: [
      "SchedAI attempts to generate schedules based on selected subjects, selected sections, class days, class times, scheduling preferences, and conflict detection rules.",
      "SchedAI tries to prevent overlapping class meetings. However, it does not guarantee that every possible university rule or enrollment condition is checked. It does not guarantee official approval, section availability, professor stability, room stability, file freshness, complete conflict detection, or the best possible enrollment choice."
    ]
  },
  {
    id: "enrollment",
    title: "No Enrollment Actions",
    body: [
      "SchedAI does not enroll students in classes. It does not reserve slots, submit forms, interact with university systems, or perform registration actions.",
      "Any enrollment action must be done through the official university enrollment system or authorized university process."
    ]
  },
  {
    id: "exports",
    title: "Exports and Shared Schedules",
    body: [
      "SchedAI may allow users to export schedules as PNG or PDF files. You are responsible for how you use, share, submit, or publish exported schedules.",
      "Exported schedules are for planning and reference only. They should not be treated as official proof of enrollment."
    ]
  },
  {
    id: "storage",
    title: "Local Session Storage",
    body: [
      "SchedAI may save selected subjects, parsed sections, preferences, generated schedules, and completed schedules in your browser storage so refreshing the page does not immediately reset your session.",
      "You can clear this information by using Reset Session or by clearing your browser storage."
    ]
  },
  {
    id: "acceptable-use",
    title: "Acceptable Use",
    body: [
      "You agree not to use SchedAI to upload files you are not allowed to use, misrepresent generated schedules as official enrollment records, attack or disrupt the application, attempt to bypass browser or hosting limits, use the application for unlawful or harmful purposes, or claim SchedAI is an official university system when it is not.",
      "You are responsible for using the application responsibly and lawfully."
    ]
  },
  {
    id: "availability",
    title: "Availability",
    body: [
      "SchedAI may be available locally during development or through a hosted website. The application may be updated, changed, unavailable, or removed at any time.",
      "There is no guarantee of uninterrupted access."
    ]
  },
  {
    id: "warranty",
    title: "No Warranty",
    body: [
      "SchedAI is provided as is and as available. No warranty is given that the application will be error-free, uninterrupted, fully accurate, or suitable for every university schedule format.",
      "Use SchedAI at your own discretion."
    ]
  },
  {
    id: "liability",
    title: "Limitation of Liability",
    body: [
      "To the fullest extent allowed by applicable law, the creator of SchedAI is not responsible for losses, damages, enrollment issues, missed classes, incorrect schedules, rejected enrollments, academic consequences, or other problems resulting from use of the application.",
      "You are responsible for verifying all schedule information with your official university system."
    ]
  },
  {
    id: "changes",
    title: "Changes to These Terms",
    body: [
      "These Terms of Use may be updated from time to time. When changes are made, the effective date may be updated.",
      "Continued use of SchedAI after changes means you accept the updated terms."
    ]
  },
  {
    id: "contact",
    title: "Contact",
    body: [
      "For questions about SchedAI, contact Karl Austin B. Pavia through Arxeni."
    ]
  }
];

export default function TermsPage() {
  return (
    <LegalPage
      eyebrow="Terms"
      title="Terms of Use"
      intro="These terms describe how SchedAI should be used. By using the schedule generator, section picker, export tools, or preview features, you agree to use them responsibly."
      documentTitle="University schedule planning terms"
      documentSummary="Effective July 13, 2026. Covers schedule parsing, generated timetables, exports, user responsibility, and enrollment planning limits."
      sections={sections}
    />
  );
}
